before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  
stages:
  - run_tests
  - build_image
  
build_image:
  stage: build_image
  script:
    - docker build -t registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest .
    - docker push registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest
  only:
    - master

run_tests:
  stage: run_tests
  script:
    - docker build -t {{ cookiecutter.project_name }}_test:latest  . --file DockerfileCI
    - docker run {{ cookiecutter.project_name }}_test
