before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  
stages:
  - run_tests
  - build_image
  
build_image:
  stage: build_image
  script:
    - docker build -t registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest .
    - docker push registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest
  only:
    - master

run_tests:
  stage: run_tests
  variables:
    DJANGO_SETTINGS_MODULE: {{ cookiecutter.project_name }}.settings.test
  script:
    - pip install -r requirements/test/requirements.txt
    - flake8 .
    - pytest
    - ./manage.py behave
