version: '3.2'

services:
  aaa:
    image: registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest
    ports:
      - {{ cookiecutter.port }}:80
    networks:
      - {{ cookiecutter.project_name }}_net
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    networks:
      - {{ cookiecutter.project_name }}_net
    environment:
      POSTGRES_PASSWORD: s7RXvwMyR9WfQmx88evkhUk85
      POSTGRES_DB: {{ cookiecutter.project_name }}
    volumes:
      - {{ cookiecutter.project_name }}_data:/var/lib/postgresql/data

networks:
  {{ cookiecutter.project_name }}_net:
    external: true

volumes:
  {{ cookiecutter.project_name }}_data:
    external: true
