version: '3.7'

services:
  {{ cookiecutter.project_name }}:
    image: registry.gitlab.com/{{ cookiecutter.project_owner }}/{{ cookiecutter.project_name }}:latest
    networks:
      - traefik
      - {{ cookiecutter.project_name }}_net
    deploy:
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.http.services.{{ cookiecutter.project_name }}.loadbalancer.server.port: '80'

        swarmpit.service.deployment.autoredeploy: 'true'

        traefik.http.routers.{{ cookiecutter.project_name }}-https.tls: 'true'
        traefik.http.routers.{{ cookiecutter.project_name }}-https.rule: Host(`{{ cookiecutter.deployment_host }}`)
        traefik.http.routers.{{ cookiecutter.project_name }}-https.entrypoints: https
        traefik.http.routers.{{ cookiecutter.project_name }}-https.service: {{ cookiecutter.project_name }}
        traefik.http.routers.{{ cookiecutter.project_name }}-https.tls.certresolver: letsencrypt

        traefik.http.routers.{{ cookiecutter.project_name }}-http.entrypoints: http
        traefik.http.routers.{{ cookiecutter.project_name }}-http.rule: Host(`{{ cookiecutter.deployment_host }}`)
        traefik.http.routers.{{ cookiecutter.project_name }}-http.service: {{ cookiecutter.project_name }}
        traefik.http.routers.{{ cookiecutter.project_name }}-http.middlewares: {{ cookiecutter.project_name }}-https-redirect
        traefik.http.middlewares.{{ cookiecutter.project_name }}-https-redirect.redirectscheme.scheme: https

  pgsql:
    image: postgres
    networks:
      - {{ cookiecutter.project_name }}_net
    environment:
      POSTGRES_PASSWORD: s7RXvwMyR9WfQmx88evkhUk85
      POSTGRES_DB: {{ cookiecutter.project_name }}
    volumes:
      - {{ cookiecutter.project_name }}_data:/var/lib/postgresql/data

networks:
  {{ cookiecutter.project_name }}_net:
  traefik:
    external: true

volumes:
  {{ cookiecutter.project_name }}_data:
